<?php
// $Id: yamm_api.module,v 1.8 2010/05/12 16:20:39 pounard Exp $

/**
 * @file
 * Yamm common API.
 */

/*
 * Client <-> server transaction status constants.
 *
 * The only success flag is WAITING or FINISHED in case of client response.
 * All others are failures.
 *
 * They are also used as stored value for logging purposes.
 */
define('YAMM_TRANSACTION_STATUS_WAITING',  1); // Awaiting for client pull.
define('YAMM_TRANSACTION_STATUS_CANCELED', 2); // Canceled by client.
define('YAMM_TRANSACTION_STATUS_FINISHED', 3); // Finished.
define('YAMM_TRANSACTION_STATUS_TIMEOUT',  4); // Timeout, canceled by server.
define('YAMM_TRANSACTION_STATUS_HOSTDOWN', 5); // Server is down before pushing.
define('YAMM_TRANSACTION_STATUS_RUNNING',  6); // Client is already running a transaction.
define('YAMM_TRANSACTION_STATUS_UNKNOWN',  7); // Client does not known the method.
define('YAMM_TRANSACTION_STATUS_DENIED',   8); // Server denied pull.
define('YAMM_TRANSACTION_STATUS_OUTDATED', 9); // Client does not respond the right protocol.

define('YAMM_METHOD_SYNC', 'yamm_method_sync');

// Variable: debug mode (set to TRUE or FALSE).
define('YAMM_OPT_DEBUG', 'yamm_opt_debug');

/**
 * Implementation of hook_menu().
 */
function yamm_api_menu() {
  $items = array();

  $items['admin/yamm'] = array(
    'title' => 'Yamm',
    'description' => "Configure and manage synchronisation server",
    'position' => 'left',
    'weight' => 20,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/yamm/global'] = array(
    'title' => 'Common options',
    'description' => 'Edit Yamm API common options',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('yamm_api_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'yamm_api.admin.inc',
  );

  return $items;
}

/**
 * Implementation of hook_perms().
 */
function yamm_api_perms() {
  return array(
    'administer sync server',
    'administer sync client',
    'launch sync jobs');
}

/**
 * Implementation of hook_yamm_entities().
 */
function yamm_api_yamm_entities() {
  $items = array();
  $items['content'] = array(
    'name' => t('Content type'),
    'class' => 'Yamm_Entity_Content',
  );
  $items['node'] = array(
    'name' => t('Node'),
    'base_table' => 'node',
    'update_field' => 'changed',
    'class' => 'Yamm_Entity_Node',
  );
  $items['term'] = array(
    'name' => t('Taxonomy term'),
    'base_table' => 'term_data',
    'class' => 'Yamm_Entity_Term',
  );
  $items['vocabulary'] = array(
    'name' => t('Taxonomy vocabulary'),
    'class' => 'Yamm_Entity_Vocabulary',
  );
  $items['user'] = array(
    'name' => t('User'),
    'base_table' => 'users',
    'class' => 'Yamm_Entity_User',
  );
  $items['file'] = array(
    'name' => t('File'),
    'class' => 'Yamm_Entity_File',
  );
  return $items;
}

/**
 * Implementation of hook_oox_registry().
 */
function yamm_api_oox_registry() {
  $items[] = array();
  $items['yamm_entity'] = array(
    'class' => 'Yamm_EntityRegistry',
    'hook' => 'yamm_entities',
  );
  return $items;
}

/**
 * Implementation of hook_xmlrpc().
 */
function yamm_api_xmlrpc() {
  return array(
    array(
      'yamm.hello',
      'yamm_api_hello_cb',
      array('boolean'),
      t('Simple hello')
    ),
  );
}

/**
 * Get file mimetype using the maximum methods possible, with a default
 * fallback to file_get_mime().
 * 
 * @param object $file
 *   Drupal file database row.
 * @param boolean $set = TRUE
 *   (optional) Set new mime type to file.
 * 
 * @return string
 *   Detected file mimetype.
 */
function yamm_api_file_get_mime($file, $set = TRUE) {
  if (function_exists('mimedetect_mime')) {
    $mime = mimedetect_mime($file);
  }
  else {
    $mime = file_get_mimetype($file->filename);
  }

  if ($set) {
    $file->filemime = $mime;
  }

  return $mime;
}

/**
 * Implementation of hook_flush_caches().
 */
function yamm_api_flush_caches() {
  return array('cache_yamm');
}

/**
 * Get hard-coded known client <-> server methods
 * For push only purposes.
 */
function yamm_api_push_methods() {
  return array(
    'yamm_sync' => t("Full content synchronisation job"));
}

function yamm_api_push_method_exists($method) {
  return array_key_exists($method, yamm_api_push_methods());
}

function yamm_api_get_status_localized_string($status) {
  switch ($status) {
    case YAMM_TRANSACTION_STATUS_WAITING:
      return t("server waiting pull");
      break;
    case YAMM_TRANSACTION_STATUS_CANCELED:
      return t("client canceled");
      break;
    case YAMM_TRANSACTION_STATUS_FINISHED:
      return t("finished");
      break;
    case YAMM_TRANSACTION_STATUS_TIMEOUT:
      return t("timeout");
      break;
    case YAMM_TRANSACTION_STATUS_HOSTDOWN:
      return t("server is down");
      break;
    case YAMM_TRANSACTION_STATUS_RUNNING:
      return t("client says already running");
      break;
    case YAMM_TRANSACTION_STATUS_UNKNOWN:
      return t("client says unknown method");
      break;
    case YAMM_TRANSACTION_STATUS_OUTDATED:
    	return t("client runs an outdated version");
    default:
      return t("unknown");
  }
}

/**
 * Clean given base url. Any trailing path after hostname will be kept, only
 * last trailing slash will be omited.
 * 
 * @param string $url
 *   Url in which to extract base url.
 * @return string
 *   Cleaned up url, without http://, and without trailing slash
 */
function yamm_api_clean_baseurl($url) {
  preg_match('/^(http:\/\/|)(.*?)(\/+|)$/', $url, $matches);
  return $matches[2];
}

/**
 * Check that URL starts with http:// and finish with a trailing slash.
 * If not, fix it.
 * 
 * @param string $url
 * @return string
 *   Well formated url
 */
function yamm_api_clean_url($url) {
  $url = check_url($url);
  if (! preg_match('/^http:\/\/.*$/', $url)) {
    $url = 'http://' . $url;
  }
  if (! preg_match('/^.*\/$/', $url)) {
    $url .= '/';
  }
  return $url;
}

/**
 * Get clean url for xmlrpc calls
 *
 * @param string $url
 * @return string
 *   Well formated url
 */
function yamm_api_xmlrpc_clean_url($url) {
  return yamm_api_clean_url($url) . 'xmlrpc.php';
}

/**
 * Wrapper method for xmlrpc() to reformat url and handle error in our way.
 *
 * @param string $url
 * @param string $method
 * @param ...
 *   Other parameters
 * @return mixed
 *   Array (xmlrpc results) in case of success
 *   FALSE else
 */
function yamm_api_xmlrpc_call($url, $method) {
  $args = func_get_args();

  // Shift this method args
  $url = array_shift($args);
  $method = array_shift($args);

  $url = yamm_api_xmlrpc_clean_url($url);

  // Unshift parameters in the right order, starting with user/pass
  array_unshift($args, $method);
  array_unshift($args, $url);

  $result = call_user_func_array('xmlrpc', $args);

  if ($result === FALSE) {
    if ($error = xmlrpc_error()) {
      watchdog('yamm', 'Unable to reach @url (xmlrpc error @errno : "@errmsg") while calling @method with @args', array(
        '@url' => $url, '@errno' => $error->code, '@errmsg' => $error->message, '@method' => $method, '@args' => print_r($args, TRUE)), WATCHDOG_ERROR);
      return FALSE;
    }
  }

  return array('data' => $result, 'status' => TRUE);
}

/**
 * Internal wrapper to create uuid using php-uuid
 */
function _yamm_api_uuid_create_old() {
  static $uuid_object = NULL;

  $ret = '';

  if (! is_resource($uuid_object)) {
    uuid_create(&$uuid_object);
  }

  uuid_make($uuid_object, UUID_MAKE_V4);
  uuid_export($uuid_object, UUID_FMT_STR, &$ret);

  return trim($ret);
}

/**
 * Check if PHP UUID pear extension is installed and enabled.
 * 
 * @return mixed
 *   FALSE if not present.
 *   1 if version older than 1.0 is installed.
 *   2 if version newer than 1.0 is enabled.
 */
function _yamm_api_uuid_enabled() {
  static $enabled;

  if (!isset($enabled)) {

    // Attempt to load extension.
    if (!$loaded = extension_loaded('uuid')) {
      // FIXME: Not supported on multithreaded servers.
      // $loaded = dl('uuid');
    }

    // Check extension version.
    if ($loaded) {

      // Check for older version.
      if (function_exists('uuid_make') && function_exists('uuid_export')) {
        $enabled = 1;
      }

      // Even if this should not be an 'else if' statement, we may have not the
      // function if the extension evolve to something else, we should fallback
      // then.
      else if (function_exists('uuid_create')) {
        $enabled = 2;
      }
    }

    // Default fallback, the library won't exists, or we can't use it because
    // they are missing functions.
    if (!isset($enabled)) {
      $enabled = FALSE;
    }
  }

  return $enabled;
}

/**
 * Generate a random uuid, time based
 *
 * @return string
 */
function yamm_api_uuid_create() {
  static $ext = NULL;

  if ($ext === NULL) {
    $ext = _yamm_api_uuid_enabled();
  }

  switch ($ext) {
    case 1:
      return _yamm_api_uuid_create_old();

    case 2:
      return uuid_create(UUID_TYPE_RANDOM);

    default:
      return str_replace(".", "", (string) uniqid(rand(), TRUE));
  }
}

/**
 * We are never going to do updates on this table, save is only insert
 *
 * @param string $uuid
 * @param string $type
 * @param int|string $identifier
 * 
 * @return boolean
 *   TRUE in case of success, FALSE if already exists or conflicts
 */
function yamm_api_uuid_save($uuid, $type, $identifier) {
  db_query("INSERT INTO {yamm_uuid} (uuid, type, identifier) VALUES ('%s', '%s', '%s')", array($uuid, $type, $identifier));
  return (bool) db_error();
}

/**
 * Delete a UUID entry.
 *
 * @param string $uuid
 *   UUID to delete.
 *
 * @return void
 */
function yamm_api_uuid_delete($uuid) {
  db_query("DELETE FROM {yamm_uuid} WHERE uuid = '%s'", array($uuid));
}

/**
 * Load corresponding uuid line from database. This method will be usefull for
 * client at pull time.
 * 
 * Never, ever, attempt to implement a static cache here, because within the
 * same execution flow, objects will be added and removed and this will cause
 * client crashes at parse time.
 *
 * @param string $uuid
 * 
 * @return object
 */
function yamm_api_uuid_load($uuid) {
  return db_fetch_object(db_query("SELECT * FROM {yamm_uuid} WHERE uuid = '%s' LIMIT 1", $uuid));
}

/**
 * Load corresponding uuid line from database
 * This method will be usefull for client at pull time
 *
 * @param string $uuid
 * @return object
 */
function yamm_api_uuid_get($type, $identifier) {
  return db_result(db_query("SELECT uuid FROM {yamm_uuid} WHERE type = '%s' and identifier = '%s' LIMIT 1", $type, $identifier));
}

/**
 * Implementation of hook_oox_api().
 */
function yamm_api_oox_api() {
  return array(
    // Core exceptions.
    'Yamm_EntityException' => 'lib/Yamm/Entity.php',
    'Yamm_Entity_ClassNotFoundException' => 'lib/Yamm/Entity.php',
    'Yamm_Entity_UnknownUuidException' => 'lib/Yamm/Entity.php',
    // Entities.
    'Yamm_Entity' => 'lib/Yamm/Entity.php',
    'Yamm_EntitySettingsAbstract' => 'lib/Yamm/Entity.php',
    'Yamm_Entity_Content' => 'lib/Yamm/Entity/Content.php',
    'Yamm_Entity_ContentSettings' => 'lib/Yamm/Entity/Content.php',
    'Yamm_Entity_File' => 'lib/Yamm/Entity/File.php',
    'Yamm_Entity_FileSettings' => 'lib/Yamm/Entity/File.php',
    'Yamm_Entity_Node' => 'lib/Yamm/Entity/Node.php',
    'Yamm_Entity_Term' => 'lib/Yamm/Entity/Term.php',
    'Yamm_Entity_TermSettings' => 'lib/Yamm/Entity/Term.php',
    'Yamm_Entity_User' => 'lib/Yamm/Entity/User.php',
    'Yamm_Entity_UserSettings' => 'lib/Yamm/Entity/User.php',
    'Yamm_Entity_View' => 'lib/Yamm/Entity/User.php',
    'Yamm_Entity_Vocabulary' => 'lib/Yamm/Entity/Vocabulary.php',
    'Yamm_Entity_VocabularySettings' => 'lib/Yamm/Entity/Vocabulary.php',
    // Entity handling API.
    'Yamm_EntityFactory' => 'lib/Yamm/EntityFactory.php',
    'Yamm_EntityFetcherInterface' => 'lib/Yamm/EntityFetcher.php',
    'Yamm_EntityFetcher' => 'lib/Yamm/EntityFetcher.php',
    'Yamm_EntityFetcher_Xmlrpc' => 'lib/Yamm/EntityFetcher/Xmlrpc.php',
    'Yamm_EntityParser' => 'lib/Yamm/EntityParser.php',
    'Yamm_EntityRegistry' => 'lib/Yamm/EntityRegistry.php',
    // File handling.
    'Yamm_FileFetcherInterface' => 'lib/Yamm/FileFetcher.php',
    'Yamm_FileFetcher' => 'lib/Yamm/FileFetcher.php',
    'Yamm_FileFetcher_Http' => 'lib/Yamm/FileFetcher/Http.php',
    // Transaction hanling.
    'Yamm_Server' => 'lib/Yamm/Server.php',
    'Yamm_TransactionHelper' => 'lib/Yamm/TransactionHelper.php',
  );
}

/**
 * Bootstrap entity subsystem, load all needed PHP files.
 */
function yamm_api_bootstrap_entity() {
  static $loaded = FALSE;

  if (! $loaded) {
    // Include supported third party modules.
    $modules = array('filefield');
    foreach ($modules as $module) {
      if (module_exists($module)) {
        require_once dirname(__FILE__) . '/integration/' . $module . '.inc';
      }
    }

    $loaded = TRUE;
  }
}

/**
 * Simple hello implementation
 */
function yamm_api_hello_cb() {
  return TRUE;
}

/**
 * Invoke the yamm_api_clean_hook().
 */
function yamm_api_clean() {
  module_invoke_all('yamm_api_clean');
}

/**
 * Is the code running in debug mode?
 */
function yamm_api_debug_mode() {
  return variable_get(YAMM_OPT_DEBUG, FALSE);
}

/**
 * Log a debug message
 * 
 * @param string $message
 *   Message to send to debug
 * @param array $variables = NULL
 *   (optional) Same signature as t() function, this is the variables for
 *   message inclusion.
 * @param boolean $raw_variables = FALSE
 *   (optional) If set to TRUE, will systemtically do a print_r() of given
 *   variables if not string, instead of formating it.
 */
function yamm_api_debug($message, $variables = array(), $raw_variables = FALSE) {
  global $debug;

  // Format variables.
  foreach ($variables as $key => $variable) {
    if ($variable instanceof Yamm_Entity) {
      $variables[$key] = $variable->getType() . ' ' . $variable->getIdentifier() . ' [ ' . $variable->getUuid() . ' ]'; 
    }
  }

  // If daemoncli is in debug mode, output into console.
  if ($debug) {
    if ($variables === NULL) {
      print($message . "\n");
    }
    else {
      $t = get_t();
      print($t($message, $variables) . "\n");
    }
  }

  if (yamm_api_debug_mode()) {
    watchdog('yamm', $message, $variables, WATCHDOG_DEBUG);
  }
}
